export const DB = [
  {
    month: "Jan, 21",
    content: {
      movies: [
        "Wonder Woman 1984",
        "В скорлупе",
        "Необычный цыпленок",
        "Чип и Дейл",
        "Все не так",
        "Два бурундука и одна мисс",
        "Соперники",
        "Запас на зиму",
        "Испорченный отдых",
        "Любители игрушек",
        "Верхом на ветке",
        "Кукурузные хлопья",
        "Дональд - яблочная сердцевина",
        "Работа за орехи",
        "Сражение с драконом",
        "На дереве",
        "Завтрак для троих",
        "Пища для вражды",
        "Klaus",
        "Проект Анна Николаевна. Спецвыпуск",
        "Love and Monsters",
        "Ночь перед Рождеством",
      ],
      tv_shows: [
        "Рождественская история (1st)",
        "Wayne (1st)",
        "Дедушка (mini)",
        "Как извести любовницу за 7 дней (mini)",
      ],
      comics: [
        "Лига Справедливости. Тайное общество",
        "Лига Справедливости. Дарксайд",
        "Бэтмен. Мистер Фриз",
        "Бэтмен. Список",
        "Бэтмен. Психушка Джокера. Ядовитый Плющ",
        "Бэтмен. Психушка Джокера. Двуликий",
        "Бэтмен. Тёмный рыцарь. Легенды. Санктум",
        "Бэтмен. Тёмный рыцарь. Легенды. Образы",
        "Бэтмен. Detective Comics. И хрюкотали зелюки",
        "Бэтмен. Санта-Кляус едет в город",
        "Бэтмен. Приключения. Новогодний спецвыпуск",
        "Бэтгерл. Приключения. Рождественский беспредел",
      ],
      games: [
        { title: "11-11: Memories Retold", perfect: false },
        { title: "In Verbis Virtus", perfect: false },
        { title: "Neighbors Back from Hell", perfect: true },
      ],
      books: [],
    },
  },
  {
    month: "Feb, 21",
    content: {
      movies: [
        "Аванпост",
        "Сказания Средиземноморья",
        "Midnight Sky",
        "Django Unchained",
        "The Revenant",
        "Ведьмина служба доставки",
        "Outsider",
        "Gangs of New York",
        "News of the World",
      ],
      tv_shows: ["Cobra Kai (3rd)", "The Watch (1st)", "Топи (1nd)"],
      comics: [
        "Бэтмен. Харли Квинн",
        "Харли Квинн. Да здравствует Харливуд",
        "Бэтмен. Убойная прогулка",
      ],
      games: [
        { title: "We Were Here", perfect: true },
        { title: "Sniper Elite: Nazi Zombie Army 2", perfect: false },
        { title: "BIT.TRIP RUNNER", perfect: false },
      ],
      books: [],
    },
  },
  {
    month: "Mar, 21",
    content: {
      movies: [
        "Croods 2",
        "Outside the Wire",
        "Withes",
        "Highwaymen",
        "Лига Справедливости Зака Снайдера",
        "Годзилла против Конга",
      ],
      tv_shows: ["Vikings (6th)", "The Expanse (5th)", "Snowpiercer (2nd)"],
      comics: [
        "Бэтмен. Ночь Пингвина",
        "Бэтмен. Разговор на двоих",
        "Бэтмен. Такая типа семья",
        "Бэтмен. Жатва",
        "Бэтмен. Укус акулы",
        "Бэтмен. Вопрос доверия",
      ],
      games: [{ title: "Warhammer: Vermintide 2", perfect: false }],
      books: [],
    },
  },
  {
    month: "Apr, 21",
    content: {
      movies: [
        "Pacific Rim",
        "Godzilla (1998)",
        "Родные",
        "Охотник на монстров",
        "Greenland",
        "The Fast and the Furious ",
      ],
      tv_shows: [],
      comics: [
        "Бэтмен. Психушка Джокера. Пингвин",
        "Бэтмен. Леденящий ужас",
        "Болотная тварь. Время святых",
        "Боун. Книга 9",
      ],
      games: [
        { title: "Left 4 Dead 2", perfect: false },
        { title: "Spyro Reignited Trilogy", perfect: false },
      ],
      books: [],
    },
  },
  {
    month: "May, 21",
    content: {
      movies: [
        "Mummy",
        "Mummy Returns",
        "А зори здесь тихие",
        "Hitman's Bodyguard",
        "Pacifix Rim 2",
        "Форсаж 9",
      ],
      tv_shows: [
        "Танцы (1st)",
        "Жуки (2nd)",
        "Чикатило (1st)",
        "Вампиры средней полосы (1st)",
        "Ивановы-Ивановы (5th)",
        "Happy End (1st)",
        "",
        "",
        "",
        "",
        "",
      ],
      comics: [],
      games: [
        { title: "Ghostrunner", perfect: false },
        { title: "We Were Here Too", perfect: false },
      ],
      books: [],
    },
  },
  {
    month: "Jun, 21",
    content: {
      movies: [
        "The Lord of the Rings: The Fellowship of the Ring",
        "The Lord of the Rings: Two Towers",
        "The Lord of the Rings: The Return og the King",
        "Телохранитель жены киллера",
        "Гнев человеческий",
      ],
      tv_shows: [],
      comics: [],
      games: [],
      books: [],
    },
  },
  {
    month: "Jul, 21",
    content: {
      movies: ["Bad Boys"],
      tv_shows: ["Пищеблок (1st)", "Sweet Tooth (1st)"],
      comics: [],
      games: [],
      books: [],
    },
  },
  {
    month: "Aug, 21",
    content: {
      movies: [
        "Bad Boys 2",
        "Bad Boys 3",
        "Pirates Of The Caribbean: The Curse of the Black Pearl",
      ],
      tv_shows: [],
      comics: ["Новые Люди Икс. Том 5. Одним меньше"],
      games: [
        { title: "Nephise: Ascension", perfect: true },
        { title: "Zenko: A Fox Tale", perfect: false },
        { title: "Strange Brigade", perfect: false },
      ],
      books: [],
    },
  },
  {
    month: "Sep, 21",
    content: {
      movies: [
        "The Witcher: Nightmare of the Wolf ",
        "Kingdom: Ashin of the North",
        "Pirates Of The Caribbean: Dead Man's Chest",
        "Pirates Of The Caribbean: At World's End",
        "Kate",
        "Army of the Dead",
      ],
      tv_shows: ["Lucifer ((5/2)th, 6th)", "Sex Educations (3rd)"],
      comics: [
        "Каратель MAX. Рождение",
        "Бессмертный Железный Кулак. Том 1",
        "Бессмертный Железный Кулак. Том 2",
      ],
      games: [{ title: "Tok", perfect: true }],
      books: [],
    },
  },
  {
    month: "Oct, 21",
    content: {
      movies: ["Веном 2"],
      tv_shows: ["The North Water"],
      comics: [
        "Бессмертный Железный Кулак. Том 3",
        "Настоящие охотники за приведениями",
        "Блюз дворовых собак",
        "Кейдж",
      ],
      games: [],
      books: [],
    },
  },
  {
    month: "Nov, 21",
    content: {
      movies: [],
      tv_shows: [
        "Squid Game (1st)",
        "Проект Анна Николаевна (2nd)",
        "Трудные подростки (3rd)",
      ],
      comics: [],
      games: [
        { title: "Batman: Arkham City", perfect: true },
        { title: "Human: Fall Flat", perfect: true },
        { title: "Kingdom Classic", perfect: false },
        { title: "Pluviophile", perfect: true },
        { title: "Snake Force", perfect: true },
        { title: "Drizzlepath", perfect: false },
        { title: "Bottle", perfect: true },
      ],
      books: [],
    },
  },
  {
    month: "Dec, 21",
    content: {
      movies: [
        "Человек-паук: Нет пути домой",
        "Погребальные байки",
        "Братья",
        "Ворошиловский стрелок",
      ],
      tv_shows: ["Патриот (2nd)"],
      comics: [],
      games: [
        { title: "Aragami", perfect: false },
        { title: "Drizzlepath: Deja Vu", perfect: true },
      ],
      books: [],
    },
  },
  {
    month: "January, 22",
    content: {
      movies: [
        "Последний богатырь. Корень зла",
        "Девчата",
        "Хоббит. Пустошь Смауга",
        "Хоббит. Битва пяти воинств",
        "Ледниковый период",
      ],
      tv_shows: [
        "Плохая дочь (мини)",
        "Любимые женщины Казановы (мини)",
        "Witcher S2",
        "Форт Боярд S8",
        "Аркейн S1",
      ],
      comics: [],
      games: [
        { title: "Assassin's Creed Unity", perfect: false },
        { title: "Mirror's Edge", perfect: false },
        { title: "Injustice 2", perfect: false },
        { title: "God of War", perfect: false },
      ],
      books: [],
    },
  },
  {
    month: "Feb, 22",
    content: {
      movies: [
        "Raya and the Last Dragon",
        "Spider-man. Into the Spider-verse",
        "Подсолнух",
        "Огонь",
      ],
      tv_shows: ["WandaVision S1", "Голяк S3"],
      comics: [],
      games: [{ title: "Marvel Spider-Man. Miles Morales", perfect: false }],
      books: [],
    },
  },
  {
    month: "Mar, 22",
    content: {
      movies: [],
      tv_shows: ["Why women kill S2"],
      comics: [],
      games: [{ title: "Marvel Spider-Man", perfect: false }],
      books: ["Живи как кот"],
    },
  },
  {
    month: "Apr, 22",
    content: {
      movies: [
        "Большой ух",
        "The Suicide Squad",
        "Troy",
        "Shang-Chi and the Legend of the Ten Rings",
      ],
      tv_shows: ["Домовенок Кузя"],
      comics: ["Отряд Икс. Том 3"],
      games: [{ title: "Mass Effect 2 LE", perfect: false }],
      books: [],
    },
  },
  {
    month: "May, 22",
    content: {
      movies: ["Зачинщики", "Маленькие чудовища", "Jungle Cruise", "Free Guy"],
      tv_shows: ["Game of Thrones. S1"],
      comics: ["Дэдпул против Карателя"],
      games: [{ title: "Star Wars Jedi: Fallen Order", perfect: false }],
      books: [],
    },
  },
  {
    month: "Jun, 22",
    movies: [
      "Mortal Kombat (2021)",
      "Fantastic Beasts: The Secrets of Dumbledore",
      "The Village",
      "Cruella",
      "Dune. Part 1",
      "Doctor Strange in the Multiverse of Madness",
    ],
    tv_shows: [],
    comics: [],
    games: [{ title: "", perfect: false }],
    books: [],
  },
  {
    month: "Jul, 22",
    movies: ["Sing", "Sing 2", "Jurassic World: Dominion"],
    tv_shows: ["Нулевой пациент. S1", "Loki. S1"],
    comics: [],
    games: [{ title: "Guardians of the Galaxy", perfect: false }],
    books: [],
  },
  // {
  //   month: "Feb, 22",
  //   movies: [],
  //   tv_shows: [],
  //   comics: [],
  //   games: [
  // { title: "", perfect: false },
  // ],
  //   books: []
  // }
];
